first iteration for import of data values
BLSQ/dhis2_cli pull request #3
Opened 2017-06-01 13:50 UTC by thejax

I know that I should make api call to verify that the data are in dhis2 in the import spec.

2017-06-01 15:20 UTC, borisrorsvort requested changes
Mostly nitpicking, nice job! Difficult for me now to really test though. Do we have a build status for the pr?

2017-06-01 15:20 UTC, borisrorsvort commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    @data_element_headers ||= @headers.select { |header| header.start_with?('de') }
The start_with is not auto explaining and need domain knowledge. maybe extract to private method with meaningful name

2017-06-01 15:20 UTC, borisrorsvort commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    @data_values_lines ||= @lines.each_with_index.map do |line, idx|
is idx index ? Then maybe rename to that

2017-06-01 15:20 UTC, borisrorsvort commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    data_values_lines.map do |data_value_line|
you can use flap_map I think. Then remove flatten at the end

2017-06-01 15:20 UTC, borisrorsvort commented on spec/models/data_values_file_spec.rb
> +    it 'does return the data elements headers' do
«returns» instead of «does return»

2017-06-01 15:20 UTC, borisrorsvort commented on spec/models/data_values_file_spec.rb
> +    it 'does return the list of data values with the values and the org unit id' do
Same here

2017-06-01 15:20 UTC, borisrorsvort commented on spec/models/data_values_file_spec.rb
> +                                                   dhis2_path: '/pM/Jk/ls/lvPW1gVZxnz',
Extract structs to let vars?

2017-06-01 15:20 UTC, borisrorsvort commented on spec/helpers/data_values_helper_spec.rb
> +    let(:data_values_helper) { DataValuesHelper.new(uri) }
You can use `subject {…}` instead

2017-06-01 15:20 UTC, borisrorsvort commented on lib/dhis2_cli/models/import/data_values_file.rb
> +        data_value[:orgUnit] = data_value_line[:dhis2_path].split('/').last
If I'm not mistaken `path` start with `/`. I know you seem to only take the last but shouldn’t we remove the first blank result?

2017-06-01 15:20 UTC, borisrorsvort commented on spec/models/data_values_file_spec.rb
> +                                                   de_2016_abc321: '324',
Is it normal that numeral values are strings here?

2017-06-01 15:20 UTC, borisrorsvort commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    @data_values_lines ||= @lines.each_with_index.map do |line, idx|
You can also use `map.with_index` at your convenience. Dunno about perf

2017-06-01 15:29 UTC, thejax commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    @data_values_lines ||= @lines.each_with_index.map do |line, idx|
I think this is rails method no ?

2017-06-01 15:29 UTC, thejax commented on lib/dhis2_cli/models/import/data_values_file.rb
> +        data_value[:orgUnit] = data_value_line[:dhis2_path].split('/').last
yep completely right

2017-06-20 07:37 UTC, thejax commented on lib/dhis2_cli/models/import/data_values_file.rb
> +    @data_values_lines ||= @lines.each_with_index.map do |line, idx|
it's a rails method, but in ruby you can do arr.map.with_index for simplier syntax

2017-06-20 09:00 UTC, thejax commented on spec/models/data_values_file_spec.rb
> +                                                   dhis2_path: '/pM/Jk/ls/lvPW1gVZxnz',
only used once so, not really necessary and I don't think it add clarity.

2017-06-20 09:00 UTC, thejax commented on spec/models/data_values_file_spec.rb
> +                                                   de_2016_abc321: '324',
yep

2017-06-20 09:00 UTC, thejax commented on spec/helpers/data_values_helper_spec.rb
> +    let(:data_values_helper) { DataValuesHelper.new(uri) }
thanks. learning every day.

2017-06-20 09:03 UTC, borisrorsvort approved these changes

2017-06-20 09:04 UTC, borisrorsvort commented
@thejax lgtm

2017-06-21 19:36 UTC, closed without merging